// Curated daily puzzle topics — rotates through these
// Diverse mix of broad, accessible topics that generate good crosswords

export const DAILY_TOPICS = [
  "Coffee",
  "Dogs",
  "Space Exploration",
  "Classic Rock",
  "Italian Food",
  "Basketball",
  "The Ocean",
  "Movies",
  "New York City",
  "Technology",
  "Gardening",
  "Jazz Music",
  "Travel",
  "Science",
  "Board Games",
  "Fashion",
  "Ancient History",
  "Cooking",
  "Soccer",
  "Books",
  "Video Games",
  "Hip Hop",
  "Wildlife",
  "Architecture",
  "Yoga",
  "Astronomy",
  "Baking",
  "Photography",
  "The Weather",
  "Musical Instruments",
  "Shakespeare",
  "Breakfast",
  "Running",
  "Art",
  "Pizza",
  "The Beach",
  "Football",
  "Television",
  "Cats",
  "Mountains",
  "Dance",
  "Chemistry",
  "Camping",
  "Sushi",
  "Magic",
  "Winter",
  "Summer",
  "Robots",
  "Dinosaurs",
  "Chocolate",
  "Baseball",
  "Podcasts",
  "The 90s",
  "Paris",
  "Tennis",
  "Flowers",
  "Sleep",
  "Cars",
  "Mythology",
  "Tea",
  "Surfing",
  "Desserts",
  "Comedy",
  "Trains",
  "The Moon",
  "Swimming",
  "Tattoos",
  "London",
  "Fishing",
  "Country Music",
  "Chess",
  "Breakfast",
  "Pottery",
  "Biking",
  "Vinyl Records",
  "Tacos",
  "Puzzles",
  "Meditation",
  "Volleyball",
  "Halloween",
  "Birthdays",
  "Rainforests",
  "Skiing",
  "Broadway",
  "Honey Bees",
  "Martial Arts",
  "Typography",
  "Birds",
  "Roller Coasters",
  "Ice Cream",
  "Podcasts",
  "Origami",
  "Coral Reefs",
  "Bridges",
  "Hot Dogs",
  "Lightning",
  "Reggae",
  "Volcanos",
  "Knitting",
  "Trivia",
  "Lemonade",
];

/**
 * Get today's daily topic based on the date.
 * Deterministic — same date always returns same topic.
 */
export function getDailyTopic(date: string): string {
  // Simple hash of date string to pick index
  let hash = 0;
  for (let i = 0; i < date.length; i++) {
    hash = (hash * 31 + date.charCodeAt(i)) & 0x7fffffff;
  }
  return DAILY_TOPICS[hash % DAILY_TOPICS.length];
}
