import { PuzzleForm } from "@/components/puzzle-form";
import { RecentPuzzles } from "@/components/recent-puzzles";

export default function Home() {
  return (
    <main className="min-h-screen flex flex-col items-center px-4 py-12 paper-texture">
      {/* Hero */}
      <div className="flex flex-col items-center gap-2 mb-10 mt-8">
        <h1 className="font-serif text-5xl sm:text-6xl tracking-tight text-crossy-ink">
          Crossy
        </h1>
        <p className="font-sans text-crossy-ink/50 text-center text-sm sm:text-base max-w-xs">
          AI-powered mini crosswords on any topic. Generate, play, share.
        </p>
        <div className="w-12 h-0.5 bg-crossy-gold/40 mt-2" />
      </div>

      {/* Form */}
      <PuzzleForm />

      {/* Recent puzzles */}
      <RecentPuzzles />

      {/* Footer */}
      <footer className="mt-16 text-center">
        <p className="font-sans text-xs text-crossy-ink/25">
          Each puzzle is uniquely generated by AI
        </p>
      </footer>
    </main>
  );
}
